### ISSUE TITLE
"Why are you making this book?" heading in the wrong task

### ISSUE THREAD

**Issue by chrislo** [raspberrypilearning/i-made-you-a-book#35]
I think the "Why are you making this book?" heading here:

https://github.com/raspberrypilearning/i-made-you-a-book/blob/master/en/step_2.md#why-are-you-making-the-book

may belong as the heading in the task below it? 

I don't think this has any impact on the projects site, but it means that the heading in [the Code Club World](https://beta.codeclubworld.org/projects/i-made-you-a-book/steps/1) version of this project appears in the wrong content block.

**Comment by tracygardner** [comment]
Tasks just contain actions for the learner to carry out. Other information goes in between the tasks, this includes headings and explanation.

**Comment by chrislo** [comment]
Thanks for explaining @tracygardner - I'd misunderstood how this worked.
